version: "3"
services:
  database:
    image: 'postgres:15.2'
    container_name: database
    ports:
      - "5434:5432"
    env_file:
      - postgres.env
  flyway:
    container_name: my-flyway
    image: flyway/flyway:latest
    command: -url=jdbc:postgresql://database:5432/postgres -schemas=public -user=postgres -password=postgres migrate
    volumes:
        - ./src/main/resources/db:/flyway/sql
    depends_on:
        - database
  talky:
    build:
      context: .
    container_name: talkyChef
    ports:
      - "8080:8080"
    depends_on:
      - flyway
    env_file:
      - server.env