export DATASOURCE_URL=
export DATASOURCE_USERNAME=
export DATASOURCE_PASSWORD=
export SCHEMA_NAME=

export KEYSTORE_PATH=
export KEYSTORE_PASSWORD=
export KEYSTORE_TYPE=
export KEYSTORE_KEY_PASSWORD=
export KEYSTORE_KEY_ALIAS=
./gradlew bootRun
