CREATE TABLE IF NOT EXISTS comments
(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id  BIGINT NOT NULL REFERENCES users,
    recipe_id BIGINT    NOT NULL REFERENCES recipes,
    date      TIMESTAMP NOT NULL,
    content   VARCHAR   NOT NULL
);