name: CD

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      - name: Build the Spring Boot application
        run: ./gradlew bootJar
      - name: Prepare SSH configuration
        run: |
          mkdir -p ~/.ssh
          echo "StrictHostKeyChecking no" > ~/.ssh/config
          chmod 600 ~/.ssh/config
          
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          chmod 600  ~/.ssh/id_rsa
      - name: Deploy Spring Boot Application
        run: |
          # Define server information
          SERVER_USER="${{secrets.SERVER_USER}}"
          SERVER_IP="${{secrets.SERVER_IP}}"
          REMOTE_APP_DIR="${{secrets.REMOTE_APP_DIR}}"
          
          # Securely transfer the JAR file to the server using SCP
          scp -o StrictHostKeyChecking=no -i  ~/.ssh/id_rsa "build/libs/voicerecipeserver-0.0.1-SNAPSHOT.jar" $SERVER_USER@$SERVER_IP:$REMOTE_APP_DIR/talkychef.jar
          
          #SSH into the server and restart the application
          ssh -o StrictHostKeyChecking=no -i  ~/.ssh/id_rsa $SERVER_USER@$SERVER_IP "cd $REMOTE_APP_DIR && ./stop.sh && nohup ./start.sh > logs.out 2>&1 &"
          sleep 7
